package com.nprotech.moneytracker.enums;

public enum SettingType {

    // MANAGEMENT
    ACCOUNT,
    WALLET,
    CURRENCY,
    MANAGE_CATEGORY,

    // CONFIG
    WEEK_STARTS_ON,
    STARTUP_SCREEN,
    LANGUAGE,
    PASSWORD,
    SMART_REMINDER,

    // BACKUP
    MANAGE_BACKUP,

    // OTHERS
    RATE_APP,
    SHARE_APP,
    SEND_FEEDBACK,
    PRIVACY_POLICY,
    TERMS_CONDITIONS,
    ABOUT,
    VERSION,

    // MANAGE BACKUP
    BACKUP_NOW,
    RESTORE_BACKUP,
    BACKUP_HISTORY,
    BACKUP_SETTINGS,

    // BACKUP SORT
    NEWEST_FIRST,
    OLDEST_FIRST,
    LARGEST_FIRST,
    SMALLEST_FIRST,

    // BACKUP FILTER
    ALL_BACKUP,
    WITH_ATTACHMENTS,
    WITHOUT_ATTACHMENTS,

    // WALLET SORT
    DEFAULT_WALLET_FIRST,
    NEWEST_WALLET_FIRST,
    OLDEST_WALLET_FIRST,
    NAME_A_Z,
    NAME_Z_A,
    LARGEST_WALLET_FIRST,
    SMALLEST_WALLET_FIRST,
}